name: OxidizeApp
options:
  bundleIdPrefix: com.oxidize
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  OxidizeApp:
    type: application
    platform: iOS
    sources: [OxidizeApp]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.oxidize.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_STRICT_CONCURRENCY: complete
        DEVELOPMENT_TEAM: "3SX65B95ZS"
        CODE_SIGN_STYLE: Automatic
    info:
      path: OxidizeApp/Info.plist
      properties:
        UIAppFonts:
          - JetBrainsMono-Regular.ttf
          - JetBrainsMono-Bold.ttf
          - JetBrainsMono-Medium.ttf
          - JetBrainsMono-SemiBold.ttf
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        CFBundleDisplayName: Oxidize
        NSHealthShareUsageDescription: "Oxidize läser din kroppsvikt från Hälsa för styrkestatistik"
        NSHealthUpdateUsageDescription: "Oxidize sparar träningspass och kroppsvikt till Hälsa"
    entitlements:
      path: OxidizeApp/OxidizeApp.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    dependencies:
      - package: Supabase
        product: Supabase
